/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import bean.ChiTietTaiKhoan;
import bean.TaiKhoan;
import bo.ChiTietTaiKhoanBo;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class HienThi extends javax.swing.JFrame {

    /**
     * Creates new form HienThi
     */
    TaiKhoan tk1 = new TaiKhoan();
    public HienThi(TaiKhoan tk) {
        initComponents();
        tk1 = tk;
        txtHoten.setText(tk.getHoTen());
        txtTien.setText(tk.getSoTien()+" VND");
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        
        tblChiTiet.setModel(defaultTableModel);
        defaultTableModel.addColumn("Ngày Giao Dịch");
        defaultTableModel.addColumn("Số Tiền Giao Dịch");
        defaultTableModel.addColumn("Ghi Chú");
        try {
            ArrayList<ChiTietTaiKhoan> list = new ChiTietTaiKhoanBo().getChiTietTaiKhoan(tk.getSoTaiKhoan());
           for(ChiTietTaiKhoan ct : list){
                String[] data = {""+ct.getNgayRutTien(),""+ct.getSoTienRutRa(),""+ct.getGhiChu()};
                defaultTableModel.addRow(data);
            }
                
        } catch (Exception ex) {
            Logger.getLogger(HienThi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        txtHoten = new javax.swing.JLabel();
        txtSoTien = new javax.swing.JLabel();
        txtTien = new javax.swing.JLabel();
        txtLichSuGiaoDich = new javax.swing.JLabel();
        btnRutTien = new javax.swing.JButton();
        btnchuyentien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hiển thị");

        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày Giao Dich", "Số tiền Giao Dich", "Ghi Chú"
            }
        ));
        jScrollPane1.setViewportView(tblChiTiet);

        txtHoten.setText("Huỳnh Quốc Thắng");

        txtSoTien.setText("Số Tiền:");

        txtLichSuGiaoDich.setText("Lịch sử giao dịch");

        btnRutTien.setText("Rút Tiền");
        btnRutTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutTienActionPerformed(evt);
            }
        });

        btnchuyentien.setText("Chuyển Tiền");
        btnchuyentien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyentienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnRutTien)
                        .addGap(18, 18, 18)
                        .addComponent(btnchuyentien))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtHoten)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSoTien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTien))
                    .addComponent(txtLichSuGiaoDich))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHoten)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoTien)
                    .addComponent(txtTien))
                .addGap(18, 18, 18)
                .addComponent(txtLichSuGiaoDich)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRutTien)
                    .addComponent(btnchuyentien))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRutTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutTienActionPerformed
        // TODO add your handling code here:
        frmRutTien frm = new frmRutTien(tk1);
        frm.setVisible(true);
    }//GEN-LAST:event_btnRutTienActionPerformed

    private void btnchuyentienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyentienActionPerformed
        // TODO add your handling code here:
        frmChuyenTien frm = new frmChuyenTien(tk1);
        frm.setVisible(true);
    }//GEN-LAST:event_btnchuyentienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaiKhoan tk = new TaiKhoan();
                new HienThi(tk).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRutTien;
    private javax.swing.JButton btnchuyentien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChiTiet;
    private javax.swing.JLabel txtHoten;
    private javax.swing.JLabel txtLichSuGiaoDich;
    private javax.swing.JLabel txtSoTien;
    private javax.swing.JLabel txtTien;
    // End of variables declaration//GEN-END:variables
}
